#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : eid-mw
Version  : 4.4.23
Release  : 1
URL      : https://github.com/Fedict/eid-mw/archive/v4.4.23.tar.gz
Source0  : https://github.com/Fedict/eid-mw/archive/v4.4.23.tar.gz
Summary  : The middleware, viewer and Firefox extension for the Belgian electronic identity card (Belgian eID)
Group    : Development/Tools
License  : AML GPL-3.0 LGPL-3.0
Requires: eid-mw-bin = %{version}-%{release}
Requires: eid-mw-data = %{version}-%{release}
Requires: eid-mw-lib = %{version}-%{release}
Requires: eid-mw-libexec = %{version}-%{release}
Requires: eid-mw-license = %{version}-%{release}
Requires: eid-mw-locales = %{version}-%{release}
BuildRequires : c_rehash
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libpcsclite)
BuildRequires : pkgconfig(libproxy-1.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(p11-kit-1)
BuildRequires : sed
BuildRequires : util-linux

%description
# BeID middleware
## About
This repository contains the software and viewer for the Belgian
electronic identity card. With this, you can:
- Communicate with secure websites that require eID authentication
- Sign documents and emails using your eID
- Using the viewer, read the identity data on eID cards, verify their
validity, and store them for future usage
- Using the provided API, do all of the above in custom applications of
your own.

%package bin
Summary: bin components for the eid-mw package.
Group: Binaries
Requires: eid-mw-data = %{version}-%{release}
Requires: eid-mw-libexec = %{version}-%{release}
Requires: eid-mw-license = %{version}-%{release}

%description bin
bin components for the eid-mw package.


%package data
Summary: data components for the eid-mw package.
Group: Data

%description data
data components for the eid-mw package.


%package dev
Summary: dev components for the eid-mw package.
Group: Development
Requires: eid-mw-lib = %{version}-%{release}
Requires: eid-mw-bin = %{version}-%{release}
Requires: eid-mw-data = %{version}-%{release}
Provides: eid-mw-devel = %{version}-%{release}
Requires: eid-mw = %{version}-%{release}
Requires: eid-mw = %{version}-%{release}

%description dev
dev components for the eid-mw package.


%package lib
Summary: lib components for the eid-mw package.
Group: Libraries
Requires: eid-mw-data = %{version}-%{release}
Requires: eid-mw-libexec = %{version}-%{release}
Requires: eid-mw-license = %{version}-%{release}

%description lib
lib components for the eid-mw package.


%package libexec
Summary: libexec components for the eid-mw package.
Group: Default
Requires: eid-mw-license = %{version}-%{release}

%description libexec
libexec components for the eid-mw package.


%package license
Summary: license components for the eid-mw package.
Group: Default

%description license
license components for the eid-mw package.


%package locales
Summary: locales components for the eid-mw package.
Group: Default

%description locales
locales components for the eid-mw package.


%prep
%setup -q -n eid-mw-4.4.23

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1572012483
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1572012483
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/eid-mw
cp %{_builddir}/eid-mw-4.4.23/COPYING %{buildroot}/usr/share/package-licenses/eid-mw/f45ee1c765646813b442ca58de72e20a64a7ddba
cp %{_builddir}/eid-mw-4.4.23/cardcomm/ctkToken/LICENSE.txt %{buildroot}/usr/share/package-licenses/eid-mw/b83641a0543ed2a51707f09223cf4e78f2139e9a
cp %{_builddir}/eid-mw-4.4.23/cardcomm/minidriver/COPYING %{buildroot}/usr/share/package-licenses/eid-mw/f45ee1c765646813b442ca58de72e20a64a7ddba
cp %{_builddir}/eid-mw-4.4.23/plugins_tools/xpi/COPYING %{buildroot}/usr/share/package-licenses/eid-mw/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install
%find_lang dialogs-beid
%find_lang eid-viewer

%files
%defattr(-,root,root,-)
/usr/lib/mozilla/pkcs11-modules/beidp11kit.json
/usr/lib/mozilla/pkcs11-modules/beidpkcs11.json

%files bin
%defattr(-,root,root,-)
/usr/bin/about-eid-mw
/usr/bin/beid-update-nssdb
/usr/bin/eid-viewer

%files data
%defattr(-,root,root,-)
/usr/share/applications/eid-viewer.desktop
/usr/share/eid-mw/eidv4.xsd
/usr/share/eid-mw/trustdir/143b8e8e.0
/usr/share/eid-mw/trustdir/9ef4b1e1.0
/usr/share/eid-mw/trustdir/belgiumrca2.pem
/usr/share/eid-mw/trustdir/belgiumrca3.pem
/usr/share/eid-mw/trustdir/belgiumrca4.pem
/usr/share/eid-mw/trustdir/c7e71426.0
/usr/share/glib-2.0/schemas/eid-viewer.gschema.xml
/usr/share/icons/hicolor/128x128/apps/eid-viewer.png
/usr/share/icons/hicolor/16x16/apps/eid-viewer.png
/usr/share/icons/hicolor/256x256/apps/eid-viewer.png
/usr/share/icons/hicolor/32x32/apps/eid-viewer.png
/usr/share/icons/hicolor/48x48/apps/eid-viewer.png
/usr/share/icons/hicolor/512x512/apps/eid-viewer.png
/usr/share/metainfo/be.belgium.eid.eidmw.metainfo.xml
/usr/share/metainfo/eid-viewer.appdata.xml
/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/belgiumeid@eid.belgium.be.xpi
/usr/share/p11-kit/modules/beid.module

%files dev
%defattr(-,root,root,-)
/usr/include/beid/rsaref220/pkcs11.h
/usr/include/beid/rsaref220/pkcs11f.h
/usr/include/beid/rsaref220/pkcs11t.h
/usr/include/beid/rsaref220/unix.h
/usr/include/eid-util/utftranslate.h
/usr/include/eid-viewer/certhelpers.h
/usr/include/eid-viewer/eid-viewer.h
/usr/include/eid-viewer/macros.h
/usr/include/eid-viewer/oslayer.h
/usr/include/eid-viewer/verify_cert.h
/usr/lib64/libbeidpkcs11.so
/usr/lib64/libeidviewer.so
/usr/lib64/pkgconfig/libbeidpkcs11.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libbeidpkcs11.so.0
/usr/lib64/libbeidpkcs11.so.0.0.0
/usr/lib64/libeidviewer.so.0
/usr/lib64/libeidviewer.so.0.1.0
/usr/lib64/pkcs11/beidpkcs11.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/beid-askaccess
/usr/libexec/beid-askpin
/usr/libexec/beid-badpin
/usr/libexec/beid-changepin
/usr/libexec/beid-spr-askpin
/usr/libexec/beid-spr-changepin

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/eid-mw/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/eid-mw/b83641a0543ed2a51707f09223cf4e78f2139e9a
/usr/share/package-licenses/eid-mw/f45ee1c765646813b442ca58de72e20a64a7ddba

%files locales -f dialogs-beid.lang -f eid-viewer.lang
%defattr(-,root,root,-)

